Unittest
be-a-step/millicord.py pull request #7
Opened 2019-06-30 04:24 UTC by Arten013

unittestが大体完成したので、一旦mergeします。

2019-07-06 05:10 UTC, lwnica approved these changes
ざっと見た感じいいと思います。というか、pythonの経験値があんまり無いので気の利いたコメントはないですね。`SampleModule` という命名が気になったくらいでしょうか。それぞれ何の sample か具体的な名前があった方がいいと思います。あと一応テストの実行コマンドを書いといてもらってもいいですか？

2019-07-06 06:15 UTC, lwnica commented
`ModuleNotFoundError: No module named 'millicord'` これが出て実行できないですね。なんか追加で設定いります？

2019-07-06 06:16 UTC, lwnica requested changes
テスト実行できない？

2019-07-14 00:56 UTC, Arten013 commented
> `ModuleNotFoundError: No module named 'millicord'` これが出て実行できないですね。なんか追加で設定いります？

おそらく、こちらの環境だとPyCharmがよしなにやってくれている部分があるため、こちらでのみ実行できる状態になってしまったっぽいので、そちらの環境でも実行できるように一旦setup.pyを作成して pip install 可能な状態にしてみます。

2019-07-21 02:18 UTC, lwnica commented
どの階層でどういうコマンドを打って unittest してるか教えてもらってもいいですか？

2019-07-21 03:01 UTC, lwnica requested changes
tests/utils の commit 忘れかな？と推測しますがどうでしょう？

2019-07-21 03:01 UTC, lwnica commented on tests/__init__.py
> +from . import utils
`from millicord.modules import utils` これで import が通るようになりました。
もしかして、tests の下に本来は `utils` がありますか？

2019-07-21 03:01 UTC, lwnica commented on tests/idol_base_test.py
> +class TestIdolBase(utils.AsyncTestMixin, unittest.TestCase):
ここで以下のエラーがでますね（一部 trace の path を編集してます）
```
Traceback (most recent call last):
  File "<python_dir>\Python\Python37\Lib\unittest\loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "<python_dir>\Python\Python37\Lib\unittest\loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "<path_to_millicord.py>\millicord.py\tests\__init__.py", line 2, in <module>
    from . import idol_base_test
  File "<path_to_millicord.py>\millicord.py\tests\idol_base_test.py", line 26, in <module>
    class TestIdolBase(utils.AsyncTestMixin, unittest.TestCase):
AttributeError: module 'millicord.modules.utils' has no attribute 'AsyncTestMixin'
```

2019-07-21 03:46 UTC, Arten013 commented
ご指摘の通り、tests/utils.pyのコミットを忘れてましたので修正しました。
テスト方法ですが、以下の通りです。

```
$ python t_helper -t <bot-token> && python setup.py test
```

2019-07-21 03:52 UTC, lwnica requested changes
token の場所が違うのでエラーになりますね。詳細はインラインコメントで

2019-07-21 03:52 UTC, lwnica commented on tests/idol_builder_test.py
> +        self.idol_path = Path(__file__).parent / \
`t_helper.py` とtokenの場所が違いますね。 `t_helper.py` は `millicord.py/idols` 以下に token を書きますが、ここでは `millicord.py/tests/idols` 以下に token を書いているようです。

2019-07-21 03:59 UTC, Arten013 commented on tests/idol_builder_test.py
> +        self.idol_path = Path(__file__).parent / \
書き込み先が不正であるバグは https://github.com/be-a-step/millicord.py/pull/7/commits/d0754e9ed717af932ba725d80f9466417016d6d3 で修正したと思ったんですが、直っていないですか？

2019-07-21 14:56 UTC, lwnica commented
一個失敗しますね
```
======================================================================
FAIL: test_find_by_path (tests.setting_test.TestYamlBase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "e:\dev\millicord\millicord.py\tests\setting_test.py", line 55, in test_find_by_path
    self.SAMPLE_YAML_DICT)
AssertionError: None != {'SampleModule1': {'int_param': 123, 'str[236 chars]al'}}

----------------------------------------------------------------------
Ran 22 tests in 19.706s

FAILED (failures=1)
Test failed: <unittest.runner.TextTestResult run=22 errors=0 failures=1>
error: Test failed: <unittest.runner.TextTestResult run=22 errors=0 failures=1>
```

2019-07-21 22:26 UTC, Arten013 commented
> 一個失敗しますね
> 
> ```
> ======================================================================
> FAIL: test_find_by_path (tests.setting_test.TestYamlBase)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "e:\dev\millicord\millicord.py\tests\setting_test.py", line 55, in test_find_by_path
>     self.SAMPLE_YAML_DICT)
> AssertionError: None != {'SampleModule1': {'int_param': 123, 'str[236 chars]al'}}
> 
> ----------------------------------------------------------------------
> Ran 22 tests in 19.706s
> 
> FAILED (failures=1)
> Test failed: <unittest.runner.TextTestResult run=22 errors=0 failures=1>
> error: Test failed: <unittest.runner.TextTestResult run=22 errors=0 failures=1>
> ```

おそらくOS間でファイルシステムが違うことが原因のエラーです。修正します。

2019-08-10 05:04 UTC, lwnica approved these changes
LGTM!

2019-08-11 02:55 UTC, merged